config/routes.rb
Qa::Application.routes.draw do

 resources :categories, :only => [:index] do
   member do
     get 'question'
   end
 end
   

  resource :user_session, :only => [:new, :create, :destroy]

  resources :users do
    resources :questions
    
    collection do
      get "my_qa"
    end
  end

  match "/activate/:token", :to => "users#activate", :as => "activate"

  resources :questions do
    resources :answers, :except => [:show, :new] do
      resources :comments, :except => [:show, :new, :edit, :index]
    end
    resources :comments, :except => [:show, :new, :edit, :index]
  end

  match "/register", :to => "users#new", :as => "register"
  match "pages/about", :to => "pages#about", :as => "about"
  match "pages/contact_us", :to => "pages#contact_us", :as => "contact_us"
  match "pages/message", :to => "pages#message", :as => "message"
  root :to => "pages#landing"

end

app/models/question.rb
class Question < ActiveRecord::Base
  require "constants"
  require 'tweeter'
  require 'url_shortner'
  
  attr_accessible :title, :description
  
  validates :title, :presence => true
  validates :description, :presence => true  

  belongs_to :user
  has_many :answers, :dependent => :destroy
  has_many :categorizations, :dependent => :destroy
  has_many :categories, :through => :categorizations
  has_many :comments, :as => :commentable

  
  belongs_to :answer, :foreign_key => 'accepted_id'
  

  default_scope order('created_at DESC')
  scope :simple_questions, where(["questions.type = 'SimpleQuestion'"])
  scope :challenge_questions, where(["questions.type = 'ChallengeQuestion'"])

  after_create :post_as_tweet

  include Constants::CategoryConstant
  include Shortner
  include Rails.application.routes.url_helpers

  def validate    
    self.errors.add(:categories, " Please categorize the question with a valid category ") if self.categories.empty?
  end

  def post_as_tweet
    message = generate_tweet_message
    Tweeter.tweet(message)
  end  

  def categorize(category)
    remove_deselected_category(category) unless category[:title].blank?
    category[:title].split.each_with_index do |_category, index|
      if _category =~ /(\w+)/ && index < MAX_NUMBER_OF_QUESTION_CATEGORIES
          unless existing_category = Category.find_by_title(_category)            
            self.categories.build(:title => sanitize_category(_category).to_s)
          else
            add_category(existing_category) unless self.categories.include?(existing_category)
          end
       end
     end
  end

  def get_categories
    categories_list = ""
    categories.each{|category| categories_list += "#{category.title} " }
    categories_list
  end


  def add_category(existing_category)    
    self.categories << existing_category
  end

  def remove_deselected_category(category)
    to_be_removed = deselected_categories(category)
    to_be_removed.each{|_category|  remove_category(_category) }
  end

  def remove_category(_category)
    self.categories.delete(_category)
  end

private
 def deselected_categories(category)
   self.categories - Category.find_all_by_title(category[:title].split)
 end

 def generate_tweet_message
   title = self.title
   hash_tags = generate_hash_tags
   question_uri = Shortner::Bitly.shorten(get_question_uri)["data"]["url"]
   hash_tag_length = hash_tags.length
   question_uri_length = question_uri.length
   title[0...(140 - (hash_tag_length + 1 + question_uri_length + 3))] + "...#{question_uri}" + " #{hash_tags}"
 end

 def generate_hash_tags
   categories = self.categories.collect{ |category| "##{category.title}" }
   categories.join(" ")
 end

 def sanitize_category(category)
   category.split.join('-')
 end

  def get_question_uri
    url_for(:action => 'show', :controller => 'questions', :id => self.id, :host => HOSTNAME)
  end
  
end
  

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new 
    @question = Question.new
    @category = @question.categories.build
  end

  def create      
    @question = (params[:question][:type].downcase == 'challenge') ? ChallengeQuestion.new(params[:question]) : SimpleQuestion.new(params[:question])
    @category = Category.new(params[:category])       # Just a stub does nothing
    @question.categorize(params[:category])
    @question.user = current_user    
    if @question.save
      flash[:notice] = "Question was successfully created and posted"
      redirect_to user_question_url(current_user, @question)
    else      
      flash.now[:error] = "Please fix the following errors"
      render "new"
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def edit
    @question = Question.find(params[:id])
    @category = Category.new(:title => @question.get_categories)
  end

  def update    
    @question = Question.find(params[:id])
    @category = Category.new(params[:category])     # Just a stub does nothing
    @question.categorize(params[:category])
    if @question.update_attributes(params[:question])
      flash[:notice] = "Your question has been successfully updated"
      redirect_to user_question_url(current_user, @question)
    else
      flash.now[:error] = "Please fix the following errors"
      render "edit"
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.answers.empty?
      if @question.destroy
        flash[:notice] = "Thread was successfully deleted"
        redirect_to user_url(current_user)
      else
        flash[:error] = "This thread could not be deleted"
        redirect_to user_question_url(current_user, @question)
      end
    else
      flash[:error] = "This thread could not be deleted"
      redirect_to user_question_url(current_user, @question)
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_each_question.html.erb
<div class="each-questions">
  <div class="question-title"> <%= link_to "#{question.title}", question_url(question) %> </div>
  <div class="question-publish-details italics dark">
    <div class="category-list">
      Categorized In: <%= render :partial => "questions/hash_tag_categories", :locals => {:question => question } %>
    </div>
    <br/>
    <% unless question.answers.empty? %>
      <%=" #{pluralize(question.answers.size, "reply", "replies")}, lastest by " + question.answers.last.user.name %>
    <% else %>
      <%= "asked by " + question.user.name  %>
    <% end %>
    <span class="posted-at" style="float:right; margin-right:10px;"> Posted on <%= question.created_at.to_datetime.strftime("%b %d %Y, %H:%M") %> </span>
  </div>
</div>

app/views/questions/_hash_tag_categories.html.erb
<% question.categories.each do |category|%>
  <%= link_to "##{category.title}", question_category_url(category) %>
<% end %>

app/views/questions/_question_block.html.erb
<div class="question">
  <div class="question-author">
    <%= gravatar_for(question.user, :s => 60) %>
  </div>

  <div class="question-details">
    <div class="question-title">
      <%= question.title %> <br/>
      <div class="smaller"> <%= question.user.name %> &nbsp;
        <span class="italics light">
          <%= question.created_at.to_datetime.strftime("%b %d %Y, %H:%M") %>
        </span>
      </div>
    </div>

    <div class="question-description">
      <%= sanitize convert_to_html(question.description) %>
      <% if current_user == question.user %>
        <div class="edit-links">
          <ul>
            <li> <%= link_to "Edit", edit_user_question_url(current_user, question) %> |</li>
            <li> <%= link_to "Delete", user_question_url(current_user, question), :method => :delete, :confirm => "Are you sure you want to delete this thread?" %> </li> |
            <li> <%= link_to "Add a comment", "#", :class => "#{question.class.to_s}_#{question.id} question-comment-link"  %> </li>
          </ul>
        </div>
      <% end %>

      <div class="question-comment-form">
        <%= render :partial => "shared/comment_form", :locals => {:obj => Comment.new,
          :type_obj => question,
          :form_method => :post, :action => question_comments_url(question) } %>
      </div>

      
      <div class="question-comments">
        <% question.comments.each do |comment| %>
          <%= render :partial => "comments/each_comment", :locals => {:comment => comment} %>
        <% end %>
      </div>      
      
    </div>
  </div>
</div>


<style>
  .question-comment-form{
    margin-top: 3em;
  }

  .comment-form{
    display: none;
  }
</style>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<% content_for :title do %>Edit - Ask a Question<% end %>

<div class="large-form round">
  <div class="form-title round"> New Question </div>
  <%= form_for @question, :as => :question, :url => user_question_url(current_user, @question), :method => :put do |f| %>

  <div class="field">
      <div class="element-label"> Type </div>
      <div class="element-field italics"> <%=  @question.type.to_s.humanize %>  </div>
  </div>

  <div class="field">
      <div class="element-label"> <%= f.label :title, "Title" %></div>
      <div class="element-field"> <%= f.text_field :title, :size =>38 %></div>
      <small class="error-message"><%= error_messages(@question,:title ) %></small>
    </div>

  <%= fields_for :category, @category do |category|  %>
      <div class="field">
        <div class="element-label"> <%= category.label :title, "Categories" %></div>
        <div class="element-field"> <%= category.text_field :title, :size =>38 %></div>
        <small class="error-message"> <%= error_messages(@question, :categories)%></small>
      </div>
    <% end %>

    <div class="field">
      <div class="element-label"> <%= f.label :description, "Description" %></div>
      <div class="element-field"> <%= f.text_area :description %></div>
      <small class="error-message"><%= error_messages(@question,:description ) %></small>
    </div>

    <div class="field">
      <div> <%= f.submit "Register", :class => 'qa-buttons' %> </div>
    </div>
  <% end %>
</div>

app/views/questions/new.html.erb
<% content_for :title do %>Ask Question<% end %>




<div class="large-form round">
  <div class="form-title round"> New Question </div>
  <%= form_for @question, :as => :question, :url => user_questions_url(current_user) do |f| %>

    <div class="field">
      <div class="element-label"> Type </div>
      <div class="element-field"> <%= f.select( "type",{"SimpleQuestion" => 'simple', 'Challenge' => 'challenge'}) %>  </div>
    </div>

    <div class="field">
      <div class="element-label"> <%= f.label :title, "Title" %></div>
      <div class="element-field"> <%= f.text_field :title, :size =>38 %></div>
      <small class="error-message"><%= error_messages(@question,:title ) %></small>
    </div>

    <%= fields_for :category, @category do |category|  %>    
      <div class="field">
        <div class="element-label"> <%= category.label :title, "Categories" %></div>
        <div class="element-field"> <%= category.text_field :title, :size =>38 %></div>
        <small class="error-message"> <%= error_messages(@question, :categories)%></small>

      </div>
    <% end %>

    <div class="field">
      <div class="element-label"> <%= f.label :description, "Description" %></div>
      <div class="element-field"> <%= f.text_area :description %></div>
      <small class="error-message"><%= error_messages(@question,:description ) %></small>
    </div>

  <div class="wmd-preview"></div>

    <div class="field">
      <div> <%= f.submit "Register", :class => 'qa-buttons' %> </div>
    </div>
  <% end %>
</div>

<script type="text/javascript" src="/javascripts/wmd/wmd.js"></script>

app/views/questions/show.html.erb
<% content_for :title do %> <%= @question.title %> <% end %>
<%= render "questions/question_block", :question => @question %>

<div class = "answers">
  <h4> Answers </h4>
  <% @question.answers.each do |answer| %>
    <%= render :partial => "answers/each_answer", :locals => {:answer => answer,
                                                    :question => @question} %>
  <% end %>
</div>

<% if current_user %>
  <div class="new-answers">
    <h4> Submit an Answer </h4>
    <div class="answer-form">
      <%= render "answers/answer_form", :question => @question %>
    </div>
  </div>
<% end %>




<script>
  $(document).ready(function(){
    $(".answers-add-comment-link").click(function(){
     
      var klasses = $(this).attr('class');
      var klass = klasses.split(" ")[0];
      var final_klass = "." + klass + "_form";     
      $("." + klass + "_form").slideToggle('slow');
      return false;
});
  })
</script> 
<style>
  .answer-comment{
    margin-top:3em;
    
}
</style>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>