config/routes.rb
Qa::Application.routes.draw do

 resources :categories, :only => [:index] do
   member do
     get 'question'
   end
 end
   

  resource :user_session, :only => [:new, :create, :destroy]

  resources :users do
    resources :questions
    
    collection do
      get "my_qa"
    end
  end

  match "/activate/:token", :to => "users#activate", :as => "activate"

  resources :questions do
    resources :answers, :except => [:show, :new] do
      resources :comments, :except => [:show, :new, :edit, :index]
    end
    resources :comments, :except => [:show, :new, :edit, :index]
  end

  match "/register", :to => "users#new", :as => "register"
  match "pages/about", :to => "pages#about", :as => "about"
  match "pages/contact_us", :to => "pages#contact_us", :as => "contact_us"
  match "pages/message", :to => "pages#message", :as => "message"
  root :to => "pages#landing"

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic      

  validates :name, :presence => true
  has_one :profile
  has_many :questions, :dependent => :destroy
  has_many :answers, :dependent => :destroy  
  
  def profile=(params)    
    self.profile.update_attributes(params)    
  end

  def to_token
    @user.perishable_token.to_s
  end

  def active?
    active
  end

  def activate!
    self.active = true
    save(:validate =>  false)
  end
  
end

app/controllers/users_controller.rb
require "will_paginate"
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])   
    if @user.save
      UserMailer.activation(@user).deliver
      unless @user.active?
        flash[:message] = "Your account has been successfully created. An email has been sent to your account. Please click the link to activate your account"
        redirect_to message_url
      end
    else
      flash.now[:error] = "Please fix the errors"
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @questions = Question.order().includes(:categories).paginate(:page => params[:page], :per_page => 10)
    render :layout => "inner"
  end

  def edit
    @user = User.find(params[:id])
  end

  def update    
    @user = current_user    
    if @user.update_attributes(params[:user])
      flash[:notice] = "Your profile has been successfully updated."
      redirect_to edit_user_url(@user)
    else      
      flash.now[:error] = "Your profile could not be updated."
      render "edit"
    end
  end

  def my_qa    
    @my_questions = current_user.questions.paginate(:page => params[:page], :per_page => 10)
    @my_answers = current_user.answers.includes(:question).paginate(:page => params[:page], :per_page => 10)
  end

  def delete
  end

  def activate
    @user = User.find_by_perishable_token(params[:token])
    if @user
      @user.activate!
      @user.reset_perishable_token!
      @user.save(:validate => false)
      flash[:notice] = "Awesome! Your account has been activated. Please log in with your email and password"
      redirect_to root_url
    else
      flash[:notice] = "Your token seems to be invalid. Please request for a new token"
      redirect_to root_url
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<% content_for :title do %>Edit Settings<% end %>


<div class="large-form">
  <div class="form-title "> Edit Profile </div>
  <%= form_for @user, :as =>:user, :url => user_url(@user), :method => :put do |f| %>
    <div class ="field">
      <div class="element-label"> <%= f.label :name, "Name"%> </div>
      <div class="element-field"> <%= f.text_field :name, :size => 38 %> </div>
      <small class="error-message"><%= error_messages(@user,:name ) %></small>
    </div>

  <%= f.fields_for :profile, @user.profile do |profile|  %>
    <div class ="field">
      <div class="element-label"> <%= profile.label :description, "About"%> </div>
      <div class="element-field"> <%= profile.text_area :description, :rows => 10, :cols => 38 %> </div>
      <small class="error-message"><%= error_messages(@user.profile,:description ) %></small>
    </div>

    <div class ="field">
      <div class="element-label"> <%= profile.label :url, "URL"%> </div>
      <div class="element-field"> <%= profile.text_field :url %> </div>
      <small class="error-message"><%= error_messages(@user.profile,:url ) %></small>
    </div>
  <% end %>

    <div class ="field">
      <div class="element-label"> Gravatar </div>
      <div class="element-field"> <%= gravatar_for(@user) %> <br/>
        <%= link_to "change","http://gravatar.com/emails" %>
      </div>
    </div>
    
    <div class="field">
      <div class="element-field"><%= f.submit "Update Settings", :class => "qa-buttons" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/my_qa.html.erb
<% content_for :title do %>My Questions<% end %>

<div class="my-questions">
  <h3> My Questions </h3>
  <div class="questions-pagination">
    <%= will_paginate @my_questions, {:next_label => "Next_", :previous_label => "_Previous"} %>
  </div>

  <% unless @my_questions.empty? %>
    <% @my_questions.each do | question | %>
      <%= render :partial => "questions/each_question", :locals => {:question => question} %>
    <% end %>
  <% else %>
    No posted questions to display on this page. <%= link_to "Post one now", new_user_question_url(current_user) %>
  <% end %>

  <div class="questions-pagination">
    <%= will_paginate @my_questions, {:next_label => "Next_", :previous_label => "_Previous"} %>
  </div>
</div>

<div class="my-answers">
  <div class="questions-pagination">
    <%= will_paginate @my_answers, {:next_label => "Next_", :previous_label => "_Previous"} %>
  </div>

  <h3> Answers </h3>
  <% unless @my_answers.empty? %>
    <% @my_answers.each do | answer | %>
      <%= render :partial => "questions/each_question", :locals => {:question => answer.question} %>
    <% end %>
  <% else %>
    No submitted answers to display on this page. <%= link_to "Try answering one now", user_url(current_user) %>
  <% end  %>

  <div class="questions-pagination">
    <%= will_paginate @my_answers, {:next_label => "Next_", :previous_label => "_Previous"} %>
  </div>

</div>

app/views/users/new.html.erb
<% content_for :title do %>Register<% end %>

<div class="error-messages">
  <% @user.errors  %>
</div>

<div class="form round">
  <div class="form-title round"> Register </div>
  <%= form_for :user, @user, :url => users_url do |f| %>

  <div class="field">
      <div class="element-label"> <%= f.label :name, "Name" %></div>
      <div class="element-field"> <%= f.text_field :name, :size =>38 %></div>
      <small class="error-message"><%= error_messages(@user,:name ) %></small>
    </div>

    <div class="field">
      <div class="element-label"> <%= f.label :email, "Email" %></div>
      <div class="element-field"> <%= f.text_field :email, :size =>38 %></div>
      <small class="error-message"><%= error_messages(@user,:email ) %></small>
    </div>

    <div class="field">
      <div class="element-label"> <%= f.label :password, "Password"  %> </div>
      <div class="element-field"> <%= f.password_field :password, :size =>38 %> </div>
      <small class="error-message"><%= error_messages(@user,:password ) %></small>
    </div>

    <div class="field">
      <div class="element-label"> <%= f.label :password_confirmation, "Password Confirmation"  %> </div>
      <div class="element-field"> <%= f.password_field :password_confirmation, :size =>38 %> </div>
      <small class="error-message"><%= error_messages(@user,:password_confirmation ) %></small>
    </div>

    <div class="field">
      <div> <%= f.submit "Register", :class => 'qa-buttons' %> </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<% content_for :title do %>Dashboard<% end %>


<% content_for :right do %>
  <div class="profile graybackground">
    <div class="profile-top">
      <div class="gravatar"> <%= gravatar_for @user, {:s => 50 } %> </div>
      <div class="title"> <%= @user.name %> </div>
    </div>
    <div class="profile-body">
      <div class="about"> <%= @user.profile.description %> </div>
    </div>
  </div>
<% end %>


<div class="primary-navigation">
  <span class = "primary-navigation-links" style ="float:left;">
    <%= link_to_unless_current "Latest Questions", user_url(current_user) %>  |
    <%= link_to_unless_current "My Q&A", my_qa_users_url %> |
    <%= link_to_unless_current "Stats", "#" %>
  </span>
  <span class="primary-navigation-links-right" style="float:right">
    <%= link_to_unless_current "New Question", new_user_question_url(current_user) %>  
  </span>
</div>

<div class="latest-questions">
  <% @questions.each do | question | %>     
    <%= render :partial => "questions/each_question", :locals => {:question => question} %>
  <% end %> 
</div>

<div class="questions-pagination">
  <%= will_paginate @questions, {:next_label => "Next_ ", :previous_label => " _Previous"} %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>