config/routes.rb
Qa::Application.routes.draw do

 resources :categories, :only => [:index] do
   member do
     get 'question'
   end
 end
   

  resource :user_session, :only => [:new, :create, :destroy]

  resources :users do
    resources :questions
    
    collection do
      get "my_qa"
    end
  end

  match "/activate/:token", :to => "users#activate", :as => "activate"

  resources :questions do
    resources :answers, :except => [:show, :new] do
      resources :comments, :except => [:show, :new, :edit, :index]
    end
    resources :comments, :except => [:show, :new, :edit, :index]
  end

  match "/register", :to => "users#new", :as => "register"
  match "pages/about", :to => "pages#about", :as => "about"
  match "pages/contact_us", :to => "pages#contact_us", :as => "contact_us"
  match "pages/message", :to => "pages#message", :as => "message"
  root :to => "pages#landing"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  
  has_many :comments, :as => :commentable
  has_one :inverse_accepted_answer, :class_name => 'Question', :foreign_key => 'accepted_id'

  validates :content, :presence => true
  
  attr_accessible :content
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(params[:answer])
    @answer.question = @question
    @answer.user = current_user
    if @answer.save
      flash[:notice] = "Your answer was successfully saved"
      redirect_to question_url(@question)
    else
      flash.now[:error] = "Please fix the following errors"  
      render :template => "questions/show"
    end
  end

  def edit
    @answer =  Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])
    if @answer.update_attributes(params[:answer])
      flash[:notice] = "Your answer has been successfully updated"
      redirect_to question_url(@answer.question)
    else
      flash.now[:error] = "Please fix the following errors"
      render "edit"
    end
  end

  def destroy
    @answer = Answer.find(params[:id])   
    if current_user == @answer.user      
      if @answer.destroy
        flash[:notice] = "Your answer has been successfully deleted"        
        redirect_to question_url(@answer.question)
      else        
        flash[:error] = "Oops your answer could not be deleted"
        redirect_to question_url(@answer.question)
      end
    end
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer_form.html.erb
<div class="round">  
  <%= form_for @answer, :as => :answer, :url => question_answers_url(@question) do |f| %>

    <%= render :partial => "answers/answer_form_fields", :locals => {:f => f, :answer => @answer}  %>

    <div class="wmd-preview"></div>
    <div class="field">
      <div> <%= f.submit "Save", :class => 'qa-buttons' %> </div>
    </div>
  <% end %>


</div>

<script type="text/javascript" src="/javascripts/wmd/wmd.js"></script>
<style>
  .answer-form{
    border: 1px solid #DEE7EC;
    background: #F4F8FA;
    padding: 10px;
    width:95%;
    margin-top: 1em;

  }

  .wmd-preview{
    padding:11px;
    background: #CCCCCC;
    margin-left:10px;
    width:94%;
}
</style>

app/views/answers/_answer_form_fields.html.erb
<div class="field">
  <div class="element-label"> <%= f.label :content, "New Answer" %></div>
  <div class="element-field"> <%= f.text_area :content %></div>
  <small class="error-message"><%= error_messages(answer,:content ) %></small>
</div>

app/views/answers/_each_answer.html.erb
<div class="each-answer">
      <div class="answer-author">
        <%= gravatar_for(answer.user)%>
      </div>

      <div class="answer-details">
        <div class="smaller"> <%= answer.user.name %> </div>
        <div class="answered">
          <% if answer.question.answer ==  answer %>
            <%= image_tag('/images/answered.gif') %>
          <% end %>
        </div>
        <span class="italics dark">
          <%= answer.created_at.to_datetime.strftime("%b %M %Y, %H:%M") %>
        </span>


        <div class="answer-description">
          <%= sanitize convert_to_html(answer.content) %>
          <% if current_user == answer.user %>
            <div class="edit-links">
              <ul>
                <li> <%= link_to "Edit", edit_question_answer_url(question, answer) %> |</li>
                <li> <%= link_to "Delete", question_answer_url(question, answer), :method => :delete, :confirm => "Are you sure you want to delete this answer?" %> | </li>
                <li> <%= link_to "Add Comment", "", :class => "Answer_#{answer.id} answers-add-comment-link" %> </li>
              </ul>
            </div>
          <% end  %>

          <div class="answer-comments-list">
            <% answer.comments.each do |comment| %>
              <%= render :partial => "comments/each_comment", :locals => {:comment => comment } %>
            <% end %>
          </div>

          <div class="answer-comment">
            <%= render :partial => "shared/comment_form", :locals => {:obj => Comment.new,
              :type_obj => answer, :form_method => :post, :action => question_answer_comments_url(question, answer)} %>
          </div>
        </div>

      </div>
    </div>


<style>
  .answered{
    float:right;
}
</style>

app/views/answers/create.html.erb
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/answers/destroy.html.erb
<h1>Answers#destroy</h1>
<p>Find me in app/views/answers/destroy.html.erb</p>

app/views/answers/edit.html.erb
<%= render "questions/question_block", :question => @answer.question %>

<div class="new-answers">
  <%= form_for @answer, :as => :answer, :url => question_answer_url(@answer.question, @answer), :method => :put do |f| %>

    <%= render :partial => "answers/answer_form_fields", :locals => {:f => f, :answer => @answer} %>

    <div class="field">
      <div> <%= f.submit "Update", :class => 'qa-buttons' %> </div>
    </div>
  <% end %>
</div>

app/views/answers/new.html.erb
<h1>Answers#new</h1>
<p>Find me in app/views/answers/new.html.erb</p>

app/views/answers/show.html.erb
<h1>Answers#show</h1>
<p>Find me in app/views/answers/show.html.erb</p>

app/views/answers/update.html.erb
<h1>Answers#update</h1>
<p>Find me in app/views/answers/update.html.erb</p>