config/routes.rb
Qa::Application.routes.draw do

 resources :categories, :only => [:index] do
   member do
     get 'question'
   end
 end
   

  resource :user_session, :only => [:new, :create, :destroy]

  resources :users do
    resources :questions
    
    collection do
      get "my_qa"
    end
  end

  match "/activate/:token", :to => "users#activate", :as => "activate"

  resources :questions do
    resources :answers, :except => [:show, :new] do
      resources :comments, :except => [:show, :new, :edit, :index]
    end
    resources :comments, :except => [:show, :new, :edit, :index]
  end

  match "/register", :to => "users#new", :as => "register"
  match "pages/about", :to => "pages#about", :as => "about"
  match "pages/contact_us", :to => "pages#contact_us", :as => "contact_us"
  match "pages/message", :to => "pages#message", :as => "message"
  root :to => "pages#landing"

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class ="flash-messages <%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/layouts/_footer_navigation.html.erb
<ul>
  <li> <%= link_to "About", about_url %> </li> |
  <li> <%= link_to "Contact", contact_us_url %> </li>
</ul>

app/views/layouts/_top_navigation.html.erb
<ul>
  <% if current_user %>
    <li> <%= link_to "Dashboard",user_url(current_user) %> </li> |
    <li> <%= link_to "Settings", edit_user_url(current_user) %> </li> |
    <li> <%= link_to "Sign out", user_session_url, :confirm => "Are you sure", :method => :delete %> </li>
  <% else %>
    <li> <%= link_to "Register", register_url %> </li> |
    <li> <%= link_to "Sign in", new_user_session_url %> </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:title) %> | easyQA </title>
    <%= yield(:css)  %>
    <%= stylesheet_link_tag "application" %>        
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div class="container ">
      <div class="header">
        <h2> easyQA </h2>
        <div class="nav">
          <%= render "layouts/top_navigation" %>          
        </div>
      </div>
      <div class="section">
        <%= render "layouts/flash_messages" %>
        <%= yield %>
      </div>

      <div class="footer">
        <div class="nav round">
          <%= render "layouts/footer_navigation" %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/inner.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>easyQA | <%= yield(:title) %></title>
    <%= csrf_meta_tag %>
    <%= yield(:css)  %>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div class="container ">
      <div class="header">
        <h2> easyQA </h2>
        <div class="nav">
          <%= render "layouts/top_navigation" %>
        </div>
      </div>

      <%= render "layouts/flash_messages" %>

      <div class="container-section">
        <div class="left-section">
          <%= yield %>
        </div>

        <div class="right-section">          
          <%= yield(:right) %>
        </div>
      </div>
      
      <div class="footer">
        <div class="nav">
          <%= render "layouts/footer_navigation" %>
        </div>
      </div>
    </div>
  </body>
</html>